-- Migration to fix 'market_prices' table schema
-- Run this in your Supabase SQL Editor

-- 1. Create the table if it doesn't exist (with proper columns)
-- Note: 'price' should be NUMERIC or FLOAT8, 'RELEASE' was a typo in previous draft if noticed
CREATE TABLE IF NOT EXISTS public.market_prices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    symbol TEXT NOT NULL,
    price NUMERIC NOT NULL DEFAULT 0,
    asset_type TEXT,
    recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Add 'asset_type' column if it's missing
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'market_prices' AND column_name = 'asset_type') THEN
        ALTER TABLE public.market_prices ADD COLUMN asset_type TEXT;
    END IF;
END $$;

-- 3. Add 'recorded_at' column if it's missing
DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'market_prices' AND column_name = 'recorded_at') THEN
        ALTER TABLE public.market_prices ADD COLUMN recorded_at TIMESTAMP WITH TIME ZONE DEFAULT NOW();
    END IF;
END $$;

-- 4. Create an index on 'recorded_at' for faster cleanup/querying
CREATE INDEX IF NOT EXISTS idx_market_prices_recorded_at ON public.market_prices (recorded_at);
CREATE INDEX IF NOT EXISTS idx_market_prices_symbol ON public.market_prices (symbol);

-- 5. Force schema cache reload (optional but good practice)
NOTIFY pgrst, 'reload schema';
