// 뉴스 룰베이스 분류기 - 키워드 사전 (R1, T05, 2026-05-23)
// AI/LLM 의존 없이 키워드 매칭만으로 4차원(코인/카테고리/감정/중요도) 분류 수행
// 소비자: T06 (news-crawl 통합), T15 (메인 표시)

export const COIN_KEYWORDS: Record<string, string[]> = {
  BTC: ["비트코인", "BTC", "bitcoin"],
  ETH: ["이더리움", "ETH", "ethereum", "이더"],
  XRP: ["리플", "XRP", "ripple"],
  SOL: ["솔라나", "SOL", "solana"],
  DOGE: ["도지", "DOGE", "dogecoin"],
  ADA: ["카르다노", "ADA", "cardano"],
  ALT: ["알트코인", "altcoin"],
  STOCK: ["S&P", "나스닥", "주식", "stock", "Nasdaq", "DJI"],
};

export const CATEGORY_KEYWORDS: Record<string, string[]> = {
  regulation: [
    "SEC",
    "규제",
    "금지",
    "승인",
    "허가",
    "가이드라인",
    "제재",
    "과세",
    "세금",
    "법안",
    "법규",
    "법원",
    "소송",
    "FATF",
  ],
  tech: [
    "업그레이드",
    "하드포크",
    "메인넷",
    "테스트넷",
    "스마트컨트랙트",
    "Layer2",
    "L2",
    "롤업",
    "스테이킹",
    "노드",
    "프로토콜",
  ],
  exchange: [
    "바이낸스",
    "업비트",
    "Binance",
    "Upbit",
    "Coinbase",
    "거래소",
    "상장",
    "상장폐지",
    "출금",
  ],
  onchain: [
    "고래",
    "온체인",
    "지갑",
    "whale",
    "holder",
    "유통량",
    "공급량",
    "채굴",
    "해시율",
    "난이도",
  ],
  etf: ["ETF", "현물 ETF", "BlackRock", "Fidelity", "Ark"],
  altcoin_news: ["알트", "altcoin", "도지", "시바", "밈코인"],
  macro: [
    "FOMC",
    "연준",
    "금리",
    "인플레이션",
    "달러",
    "환율",
    "원/달러",
    "Fed",
    "CPI",
    "PCE",
    "고용지표",
  ],
  market: [], // fallback (위 카테고리 0매치 시)
};

export const POSITIVE_KEYWORDS: Record<string, number> = {
  급등: 3,
  사상최고: 5,
  신고가: 4,
  돌파: 3,
  승인: 4,
  가결: 3,
  유입: 2,
  매수: 2,
  상승: 2,
  강세: 2,
  호재: 4,
  파트너십: 3,
  도입: 2,
  확장: 1,
  성장: 2,
  상장: 3,
  런칭: 2,
  출시: 2,
  절감: 2,
  개선: 2,
  복구: 1,
  rally: 3,
  surge: 4,
  bull: 3,
  bullish: 3,
  high: 2,
};

export const NEGATIVE_KEYWORDS: Record<string, number> = {
  폭락: -5,
  급락: -4,
  하락: -2,
  약세: -2,
  악재: -4,
  해킹: -5,
  도난: -4,
  유출: -3,
  지연: -2,
  취소: -3,
  정지: -3,
  중단: -3,
  장애: -3,
  상장폐지: -4,
  제재: -3,
  소송: -3,
  기각: -3,
  금지: -4,
  사임: -2,
  퇴진: -2,
  과세: -3,
  세금: -2,
  연기: -2,
  vulnerability: -4,
  exploit: -5,
  crash: -5,
  dump: -4,
  bear: -3,
  bearish: -3,
};

export const SOURCE_WEIGHTS: Record<string, number> = {
  코인데스크: 1.2,
  블룸버그: 1.5,
  로이터: 1.4,
  CNBC: 1.3,
  코인텔레그래프: 1.0,
  "더 블록": 1.1,
  코인포스트: 1.0,
  글래스노드: 1.2,
  코인게이프: 0.9,
};
