-- Create a table to store historical market prices
create table if not exists market_prices (
  id bigint generated by default as identity primary key,
  symbol text not null,
  date date not null,
  open numeric,
  high numeric,
  low numeric,
  close numeric,
  volume numeric,
  type text check (type in ('CRYPTO', 'STOCK')),
  created_at timestamptz default now(),
  unique(symbol, date)
);

-- Separate index for fast lookup by symbol and date
create index if not exists idx_market_prices_lookup on market_prices(symbol, date desc);

-- Enable Row Level Security (RLS)
alter table market_prices enable row level security;

-- Policy: Allow everyone to read prices
create policy "Public prices are viewable by everyone"
  on market_prices for select
  using (true);

-- Policy: Allow authenticated users (or service role) to insert prices
-- For simplicity in this personal project, we allow any authenticated user to insert
-- In a real app, you might restrict this to service_role only
create policy "Authenticated users can insert prices"
  on market_prices for insert
  with check (auth.role() = 'authenticated' or auth.role() = 'service_role');

create policy "Authenticated users can update prices"
  on market_prices for update
  using (auth.role() = 'authenticated' or auth.role() = 'service_role');
